In [1]:
import numpy as np
import pandas as pd
import graphviz
import lingam
from lingam.utils import make_dot

print([np.__version__, pd.__version__, graphviz.__version__, lingam.__version__])

np.set_printoptions(precision=3, suppress=True)
np.random.seed(1)

['1.19.5', '1.1.5', '0.19.1', '1.5.5']


In [2]:
import torch
torch.cuda.set_device(0)

torch.set_default_dtype(torch.double)
np.set_printoptions(precision=3)

In [3]:
from notears.nonlinear import NotearsMLP, notears_nonlinear
from notears import utils

# model = NotearsMLP(dims=[d, 10, 1], bias=True)
# W_est = notears_nonlinear(model, X, lambda1=0.01, lambda2=0.01)

utils.set_random_seed(1)

In [4]:
df = pd.read_csv("datasets/nhefs.csv", skiprows = 1, header=None)
df = df.fillna(-1).reset_index(drop=True)

X = df
X = (X-X.mean())/X.std()
X = X.to_numpy()
print(X)

type(X)

[[-2.176 -0.597 -0.492 ...  0.113  0.544  0.453]
 [-2.176 -0.597 -0.492 ...  0.414  0.852  0.847]
 [-2.175 -0.597 -0.492 ... -0.521 -0.587 -0.374]
 ...
 [ 1.13  -0.597 -0.492 ...  0.113 -0.305 -0.496]
 [ 1.131 -0.597 -0.492 ...  0.354 -0.086  0.091]
 [ 1.135  1.675 -0.492 ...  0.354 -0.086  0.091]]


numpy.ndarray

In [5]:
X.shape

(1629, 64)

In [6]:
n, d, s0, graph_type, sem_type = 100, 20, 20, 'ER', 'gauss'
B_true = utils.simulate_dag(d, s0, graph_type)
W_true = utils.simulate_parameter(B_true)
# np.savetxt('W_true.csv', W_true, delimiter=',')

_X = utils.simulate_linear_sem(W_true, n, sem_type)
# np.savetxt('X.csv', X, delimiter=',')
_X.shape

type(_X)

numpy.ndarray

In [ ]:
row_num = X.shape[0]
col_num = X.shape[1]

model = NotearsMLP(dims=[col_num, col_num, 1], bias=True)

W_est = notears_nonlinear(model, X, lambda1=0.01, lambda2=0.01)

In [ ]:
assert utils.is_dag(W_est)
np.savetxt('W_est.csv', W_est, delimiter=',')

In [ ]:
import pandas as pd
from lingam.utils import make_dot

result_matrix = pd.read_csv("W_true.csv", header=None)

result_matrix

In [ ]:
dot = make_dot(result_matrix)

# Save png
dot.format = 'png'

dot.render('./dag')

In [ ]:
from IPython.display import Image
Image(filename='dag.png') 